style:
    # default columns, you can override by: {columns: 3}
    columns: 2
    # maximum number of rows per page - should be computed :)
    maxRows: 24
    # upper fractions
    upperNumbers: '⁰¹²³⁴⁵⁶⁷⁸⁹'
    # lower fractions
    lowerNumbers: '₀₁₂₃₄₅₆₇₈₉'
    # default metadata to render
    renderMetadataKeys: ['time', 'tempo']
    lineWidth: 0.2
    # how many spaces between two words in verse    Každej tu[xSpaceFactor * widthOf('X')]černou
    xSpaceFactor: 2.5
    # row height(LYRICS) * ySpaceFactor is space between two rows
    ySpaceFactor: 0.6
    # red color ;)
    red: [26, 129, 255]
    # text color
    black: [0, 0, 0]
    # hilight color
    fill: [20, 20, 20]
    # chord replacements
    chordSymbols: [ 'b': '♭', '#': '♯' ]
    # ligature symbols - check if your ttf font supplies all of those ones
    ligatures: [ 'ffi': 'ﬃ', 'ffl': 'ﬄ', 'ff': 'ﬀ', 'fi': 'ﬁ', 'fl': 'ﬂ', 'ft': 'ﬅ' ]
    # translations
    sectionTitles: ['verse': 'sloka', 'chorus': 'refrén']
    # --------- fonts  [size, color, FaceLookTo fonts directory (FreeSerif is fonts/FreeSerif.ttf)]
    TITLE: [26, red, FreeSerif]
    AUTHOR: [17, red, FreeSerif]
    CHORD: [19, red, FreeSerif]
    LYRICS: [19, black, FreeSerif]
    METADATA: [17, black, FreeSerif]

