style:
    columns: 2
    maxRows: 14
    upperNumbers: '⁰¹²³⁴⁵⁶⁷⁸⁹'
    lowerNumbers: '₀₁₂₃₄₅₆₇₈₉'
    renderMetadataKeys: ['time', 'tempo']
    lineWidth: 0.2
    xSpace: 7
    red: [26, 129, 255]
    black: [0, 0, 0]
    fill: [20, 20, 20]
    TITLE: [26, red, FreeSerif]
    AUTHOR: [17, red, FreeSerif]
    CHORD: [19, red, FreeSerif]
    LYRICS: [19, black, FreeSerif]
    METADATA: [17, black, FreeSerif]
    SECTION: [19, black, FreeSerifBold]



parser:
    ligatures: [ 'ff': 'ﬀ', 'fi': 'ﬁ', 'fl': 'ﬂ', 'ffi': 'ﬃ', 'ffl': 'ﬄ', 'ft': 'ﬅ' ]


pdfrenderer:
    chordSymbols: [ 'b': '♭', '#': '♯' ]

